### PR TITLE
Update deploying-the-app-v-51-server.md

### PR DESCRIPTION
**Pull request by DenisElferink**
There is no MDOP resource for version 5.1, which used to be for previous versions. So it is clearer when the locations are mentioned where the setup sources can be found. Also there is a hotfix for the App-v management server when installed on Server 2016.

### CODE REVIEW

**Comment by brianlic-msft** [comment]
@jamiejdt Can you help with this?

**Comment by jamiejdt** [comment]
Hi,
I'd like to help you and am trying to understand what you want to do. We do have a standard pointers on how to get MDOP such as on our TechNet landing page.

On the content, the App-V client and RDS are in-box as of Windows 10 1607 but this version continues to use the App-V 5.1 Server.  As you indicate, the September servicing release contains a bug fix for this combination. This problem does not exist with the App-V 5.1 combination.

Finally, the Sequencer in the ADK is for the Windows 10 1607 version rather than the App-V 5.1 Sequencer. So far, the packages that they build are compatible.

**Comment by DenisElferink** [comment]
Hello,


First of all great articles about App-v 5.1! There is not so much information on the internet about this version.


I am working independent and was asked for a potential project to implement App-v in a company. I am experienced with 4.6 and know 5.0 but was not familiar with the latest 5.1.


So, I built an App-V 5.1 test environment on Hyper-v the last days. There were a view challenges, which took me a lot of time to figure out. And I did not find any up to date information about where to find the exactly needed installation files and how to do the installation.



Installation sources:

Your refer to MDOP. But what is meant by MDOP is a little confusing.

I found information about MDOP here: https://technet.microsoft.com/en-us/windows/bb899442.


I read this:

"MDOP is available for test and evaluation to certain MSDN<https://msdn.microsoft.com/en-us/subscriptions/downloads/default.aspx?pv=42:178> subscribers in accordance with MSDN subscription agreements"

 So, I searched in my MSDN subscription for MDOP, but could not find anything.


In the same article: "MDOP is a suite of technologies". But, where is the description of the installation sources (ISO's) of App-V? I did not find any information about it at all. By accident almost found in MSDN the ISOs:

- Application Virtualization Hosting for Desktops 5.1 (x86 and x64) - CD (Multiple Languages)

- Application Virtualization for Remote Desktop Services 5.1 (x86 and x64) - CD (Multiple Languages)


Hyper-v client integration in Windows 10:
Since the aniversary update of Windows 10 the client is integrated. I did not find this information in this article: https://technet.microsoft.com/en-us/itpro/mdop/appv-v5/how-to-deploy-the-app-v-client-51gb18030. The article says that an executable must be run to install the client.

Separate installation source for the sequencer:
The sequencer from the ISO cannot be installed on Windows 10 after the anniversary update anymore! It is not compatible anymore. I got an error that Windows 10 cannot run this version. The newest version must be installed from ADK: https://developer.microsoft.com/en-us/windows/hardware/windows-assessment-deployment-kit

Powershell:
No more gui for the client. Just powershell works. This article is not relevant anymore for the new client version, but that is not clear in the article itself: https://technet.microsoft.com/en-us/itpro/mdop/appv-v5/about-client-configuration-settings51. There is a referral to powershell, but not the text that powershell is the only option as of the new version.



Kind regards,
Denis Elferink













________________________________
Van: jamiejdt <notifications@github.com>
Verzonden: woensdag 16 november 2016 01:00
Aan: Microsoft/windows-itpro-docs
CC: DenisElferink; Author
Onderwerp: Re: [Microsoft/windows-itpro-docs] Update deploying-the-app-v-51-server.md (#76)


Hi,
I'd like to help you and am trying to understand what you want to do. We do have a standard pointers on how to get MDOP such as on our TechNet landing page.

On the content, the App-V client and RDS are in-box as of Windows 10 1607 but this version continues to use the App-V 5.1 Server. As you indicate, the September servicing release contains a bug fix for this combination. This problem does not exist with the App-V 5.1 combination.

Finally, the Sequencer in the ADK is for the Windows 10 1607 version rather than the App-V 5.1 Sequencer. So far, the packages that they build are compatible.

-

**Comment by brianlic-msft** [comment]
@jamiejdt Can you take another look?

**Comment by brianlic-msft** [comment]
@DenisElferink A Software Assurance license is required.

**Comment by DenisElferink** [comment]
Ok, I know you need a software assurance license to use the product. But the problem is that the documentation about where the installation sources are is confusing. I had a MCT MSDN subscription. I did find ISO's for App-v but did not see a section MDOP.

**Pull request closed without merging**
