### PR TITLE
Update upgrade-analytics-requirements.md

### PR DESCRIPTION
**Pull request by zdvorak**
Added an additional endpoint to be whitelisted.

### CODE REVIEW

**Comment by brianlic-msft** [comment]
@zdvorak This one already appears to be in the list.  Here's what's published now:

https://v10.vortex-win.data.microsoft.com/collect/v1
https://settings-win.data.microsoft.com/settings
https://vortex.data.microsoft.com/health/keepalive
https://settings.data.microsoft.com/qos
https://go.microsoft.com/fwlink/?LinkID=544713
https://compatexchange1.trafficmanager.net/CompatibilityExchangeService.svc/extended

**Comment by zdvorak** [comment]
The one to add was: https://vortex-win.data.microsoft.com/health/keepalive.

We currently have vortex.data and v10.vortex-win.data, but not vortex-win.data.

**Comment by brianlic-msft** [comment]
@zdvorak Ah -- got it. I've merged this in.  Thanks!

**Comment by zdvorak** [comment]
Thanks, @brianlic-msft!

**Pull request merged**
