### PR TITLE
Update configure-windows-10-taskbar.md

### PR DESCRIPTION
**Pull request by loosus456**
Just a few minor clarifications that I think may be helpful.

### CODE REVIEW

**Comment by jdeckerMS** [comment]
Thanks for your feedback! Some of your changes have been merged into the topic. A few (such as hyphenating the descriptions of the XML file and removing "by" before "using") were not because they don't comply with Microsoft content style guidelines.

**Comment by loosus456** [comment]
Thanks.

Are you guys going by a mainstream style guide or an internal one?

**Comment by jdeckerMS** [comment]
We have internal guidelines. For example, "by using" is preferred to simply "using" based on input from our localization experts -- it makes it easier for them to localize into other languages.

**Comment by loosus456** [comment]
Is it publicly published anywhere?  It might be easier going forward with those sort of things in mind.

**Comment by jdeckerMS** [comment]
We welcome input on incorrect, confusing, or missing information, but we really don't expect customers to invest their time and effort just on minor editorial issues.

**Pull request merged**
